#ifndef _TIMER0_CONFIG_H_
#define _TIMER0_CONFIG_H_

/** Options: 
             TIMER0_NORMAL 
			 TIMER0_PWM_PHASE_CORRECT
			 TIMER0_CTC
			 TIMER0_PWM_FAST
*/

#define TIMER0_MODE_OF_OPERATION  TIMER0_NORMAL

/** Options: 
             TIMER0_CLK_NO_PRESCALING
			 TIMER0_CLK_DIV_8
			 TIMER0_CLK_DIV_64
			 TIMER0_CLK_DIV_256
			 TIMER0_CLK_DIV_1024	 
*/
#define TIMER0_PRESCALER_SELECTION TIMER0_CLK_DIV_8
#endif